### ISSUE TITLE
Can't launch the tests via tarantoolctl in "Getting Started"

### ISSUE THREAD

**Issue by artur-barsegyan** [tarantool/cartridge-cli#31]
Version of the Tarantool:
```
Tarantool 2.2.1-1-g1208b4e
```

Output:
```
a.barsegyan@a getting-started-app $ pwd
/Users/a.barsegyan/Documents/getting-stated/cartridge-cli/examples/getting-started-app
a.barsegyan@a getting-started-app $ tarantoolctl rocks test

Error: could not detect test type -- no test suite for getting-started-app?
a.barsegyan@a getting-started-app $ 
```
What's the problem? If I will start tests via `./.rocks/bin/luatest` it will OK.

**Comment by artur-barsegyan** [comment]
Yeah, the issue relates to "Getting Started" example

**Comment by printercu** [comment]
`tarantoolctl rocks test` requires luarocks 3 which is available only in tarantool 2. Rockspec formats are not compatible so rockspec for v3 will not work with v2. I think "getting started" may also run on 1.10, so requested behaviour is not possible.

PS. we discourage using `ctl rocks test` because it does not support options, and luarocks does not work well with different types of deps.

**Comment by artur-barsegyan** [comment]
Ok. At now, we have removed any mentions about `tarantoolctl rocks test` from README and can close this issue.
