### ISSUE TITLE
[4pt] Get rid of flaky tests

### ISSUE THREAD

**Issue by dokshina** [tarantool/cartridge-cli#519]

**Comment by mRrvz** [comment]
Together with #527, we practically got rid of the most flaky test. But, along with #588, an [flaky test](https://github.com/tarantool/cartridge-cli/blob/a34758c4f964c2baa1c936c226dc6a062b215bb8/test/integration/failover/test_failover.py#L33) often began to appear. I don’t know what the reason is yet.

https://github.com/tarantool/cartridge-cli/pull/628/checks?check_run_id=3495207536

**Comment by DifferentialOrange** [comment]
There are still a lot of flaky tests
- No remotes with role "vshard-router" available ([job](https://github.com/tarantool/cartridge-cli/runs/4777265772?check_suite_focus=true))
- Could not fetch rock file ([job](https://github.com/tarantool/cartridge-cli/runs/4787637436?check_suite_focus=true))
- Failed to connect to bus: No such file or directory ([job](https://github.com/tarantool/cartridge-cli/runs/4787173951?check_suite_focus=true))
- Replication setup failed, instance orphaned ([job](https://github.com/tarantool/cartridge-cli/runs/4775538650?check_suite_focus=true))
- Failed to run /usr/bin/tarantoolctl rocks make ([job](https://github.com/tarantool/cartridge-cli/runs/4774642830?check_suite_focus=true))

**Comment by LeonidVas** [comment]
https://github.com/tarantool/cartridge-cli/issues/724
