### ISSUE TITLE
Consider an alternative to old-way .ignore

### ISSUE THREAD

**Issue by olegrok** [tarantool/cartridge-cli#86]
The main idea of .cartridge.ignore was to clear useless artefacts after building (e.g. node_modules/some docs temporary files)

However, now .cartridge.ignore is used before build. So, user can't control that will be packed after build.

Let's consider an alternative to old-way approach. It could be a ".cartridge.pack.ignore" or something else.

**Comment by dokshina** [comment]
I like the idea of using special file (other than `.cartridge.ignore`) to specify files to be ignored after build.

I suggest `.cartridge.cleanup` name.

So, the new build flow would be:

* Deletion files mentioned in `.cartridge.ignore`;
* Running `.cartridge.pre` script;
* Running `tarantoolctl rocks make`;
* Removing files mentioned in `.cartridge.cleanup`.

It seems logical that `.cartridge.cleanup` will use the same patterns format as `.cartridge.ignore` uses.

The alternative approach is to make `.cartridge.cleanup` executable and run it after `rocks make`.
It will be smth like `.cartridge.post`, but for performing some actions AFTER build.

**Comment by olegrok** [comment]
So, may be we should implement as part of this feature something similar to git hooks

I respect your idea to introduce ".cleanup" file - we should exclude some files from packaging into the final artefact

But we have ".cartridge.pre" and ".cartridge.post" looks as a good idea. But this names don't say "pre" or "post" what. 

Example of git-hooks: `pre-commit`, `post-commit`

I suggest to rename it to `.cartridge.pre-build` and `.cartridge.post-build`

**Comment by rosik** [comment]
I like the idea of `cartridge.pre-build` and `cartridge.post-build` scripts similar to git-hooks.

And I don't like the idea of another `.cleanup` file similar to .ignore with globs. If we speak about post-build actions, simple globs are much less functional.

And don't use periods, please.
See also #66

**Comment by knazarov** [comment]
I don't see how `.cartridge.ignore` that is executed before any build starts is useful. It's only probably useful in case if you want a very slight (maybe even unnoticable) reduction in build times because you don't copy some part of your source code into the temporary directory. 
So, the .ignore stuff should be executed after the build is complete if we keep it.

I like the pre-build and post-build as a cleaner alternative. But anyway, I'd make the pre-build and post-build a default, but keep the old behavior supported for a while, until we release a new major release of cartridge-cli, where we probably should raise an error if we meet .cartridge.ignore or .cartridge.pre with a suggestion to rename them.

**Comment by dokshina** [comment]
So, you suggest adding `.cartridge.post-build` script to be run after `rocks make` and renaming `.cartridge.pre -> .cartridge.pre-build` ?

Before the new major version release we will support the current `.cartridge.ignore` and `.cartridge.pre` behaviour, but print a deprecation message for it.

I think, that we can support the current `.cartridge.ignore + .cartridge.pre` flow for all distribution types, except `docker`. This type of packing is new and shouldn't be compatible with the old versions.

Finally, the application pack flow will be:

So, the new build flow would be:

* Running `git clean` (I think that files, ignored by `git` should be ignored anyway);
* Running `cartridge.pre-build` script;
* Running `tarantoolctl rocks make`;
* Running `cartridge.post-build` script;
